#!/usr/bin/env bash
# One-command install: clone Buzz + ZeroClaw + OpenAGI into deps/, build, install bridge.
set -euo pipefail

SKIP_RUST=0
SKIP_NPM=0
SKIP_BRIDGE=0
BUZZ_URL="${BUZZ_URL:-https://github.com/Questing-VR/buzz.git}"
ZC_URL="${ZC_URL:-https://github.com/Questing-VR/zeroclaw.git}"
OA_URL="${OA_URL:-https://github.com/Questing-VR/openAGI.git}"

for arg in "$@"; do
  case "$arg" in
    --skip-rust) SKIP_RUST=1 ;;
    --skip-npm) SKIP_NPM=1 ;;
    --skip-bridge) SKIP_BRIDGE=1 ;;
    -h|--help)
      echo "Usage: $0 [--skip-rust] [--skip-npm] [--skip-bridge]"
      exit 0
      ;;
  esac
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPS="$ROOT/deps"
mkdir -p "$DEPS"

step() { echo; echo "=== $* ==="; }

clone_dep() {
  local name="$1" url="$2"
  local path="$DEPS/$name"
  if [[ -d "$path/.git" ]]; then
    echo "deps/$name present — pull --ff-only"
    git -C "$path" pull --ff-only || echo "pull skipped"
  else
    echo "Cloning $url -> deps/$name"
    git clone --depth 1 "$url" "$path"
  fi
}

step "BuzzClawAGI install (root=$ROOT)"

step "1/4 Clone parent forks"
clone_dep buzz "$BUZZ_URL"
clone_dep zeroclaw "$ZC_URL"
clone_dep openAGI "$OA_URL"

if [[ "$SKIP_NPM" -eq 0 ]]; then
  step "2/4 OpenAGI (npm)"
  if ! command -v node >/dev/null 2>&1; then
    echo "WARN: Node not found — install Node 22+"
  else
    (cd "$DEPS/openAGI" && (npm ci 2>/dev/null || npm install))
  fi
else
  echo "Skipping npm"
fi

if [[ "$SKIP_RUST" -eq 0 ]]; then
  step "3/4 ZeroClaw + Buzz (cargo — slow)"
  if ! command -v cargo >/dev/null 2>&1; then
    echo "WARN: cargo not found — install rustup; bridge can DRY_RUN without it"
  else
    (cd "$DEPS/zeroclaw" && cargo build --release)
    (cd "$DEPS/buzz" && cargo build --release -p buzz-cli -p buzz-acp) || \
      echo "WARN: buzz-cli/buzz-acp build failed — check buzz docs"
  fi
else
  echo "Skipping rust"
fi

if [[ "$SKIP_BRIDGE" -eq 0 ]]; then
  step "4/4 Bridge (Python)"
  python3 -m pip install -r "$ROOT/bridge/requirements.txt"
  (cd "$ROOT/bridge" && python3 -m pytest tests -q --tb=line)
fi

if [[ ! -f "$ROOT/.env" && -f "$ROOT/.env.example" ]]; then
  cp "$ROOT/.env.example" "$ROOT/.env"
  echo "Created .env from .env.example"
fi

# PATH export file for start.sh
{
  echo "# generated by install.sh"
  echo "export BUZZ_PATH=\"$DEPS/buzz\""
  echo "export ZEROCLAW_PATH=\"$DEPS/zeroclaw\""
  echo "export OPENAGI_PATH=\"$DEPS/openAGI\""
  echo "export OPENAGI_URL=\"\${OPENAGI_URL:-http://127.0.0.1:43210}\""
  echo "export ZEROCLAW_ACP_CMD=\"\${ZEROCLAW_ACP_CMD:-zeroclaw acp}\""
  echo "export PATH=\"$DEPS/zeroclaw/target/release:$DEPS/buzz/target/release:\$PATH\""
} > "$DEPS/path.sh"

step "Install complete"
cat <<EOF

deps/buzz  deps/zeroclaw  deps/openAGI  + bridge/

Next:
  ./scripts/start.sh

Dry-run bridge only:
  DRY_RUN=1 ./scripts/start.sh --bridge-only
EOF
