#requires -Version 5.1
<#
.SYNOPSIS
  One-command install for BuzzClawAGI: clone/build Buzz + ZeroClaw + OpenAGI + bridge.

.USAGE
  .\scripts\install.ps1
  .\scripts\install.ps1 -SkipRust    # OpenAGI + bridge only (faster)
  .\scripts\install.ps1 -SkipNpm
#>
param(
  [switch]$SkipRust,
  [switch]$SkipNpm,
  [switch]$SkipBridge,
  [string]$BuzzUrl = "https://github.com/Questing-VR/buzz.git",
  [string]$ZeroClawUrl = "https://github.com/Questing-VR/zeroclaw.git",
  [string]$OpenAgiUrl = "https://github.com/Questing-VR/openAGI.git"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not (Test-Path (Join-Path $Root "bridge"))) {
  $Root = Get-Location
}
$Deps = Join-Path $Root "deps"
New-Item -ItemType Directory -Force -Path $Deps | Out-Null

function Write-Step($msg) { Write-Host "`n=== $msg ===" -ForegroundColor Cyan }
function Have($cmd) { return [bool](Get-Command $cmd -ErrorAction SilentlyContinue) }

function Ensure-Clone($name, $url) {
  $path = Join-Path $Deps $name
  if (Test-Path (Join-Path $path ".git")) {
    Write-Host "deps/$name already present — pulling..."
    Push-Location $path
    try { git pull --ff-only 2>$null } catch { Write-Host "pull skipped (local changes?)" }
    Pop-Location
  } else {
    Write-Host "Cloning $url -> deps/$name"
    git clone --depth 1 $url $path
  }
  return $path
}

Write-Step "BuzzClawAGI install"
Write-Host "Root: $Root"
Write-Host "This clones your three forks into deps/ and installs the bridge."

# ── clone parents ────────────────────────────────────────────────
Write-Step "1/4 Clone parent forks into deps/"
$BuzzPath = Ensure-Clone "buzz" $BuzzUrl
$ZcPath = Ensure-Clone "zeroclaw" $ZeroClawUrl
$OaPath = Ensure-Clone "openAGI" $OpenAgiUrl

# ── OpenAGI (Node) ───────────────────────────────────────────────
if (-not $SkipNpm) {
  Write-Step "2/4 OpenAGI (npm)"
  if (-not (Have "node")) {
    Write-Warning "Node.js not found. Install Node 22+ then re-run. Skipping OpenAGI npm install."
  } else {
    $nodeVer = (node -v)
    Write-Host "Node $nodeVer"
    Push-Location $OaPath
    if (Test-Path package-lock.json) { npm ci } else { npm install }
    Pop-Location
    Write-Host "OpenAGI deps installed."
  }
} else {
  Write-Host "Skipping OpenAGI npm (-SkipNpm)"
}

# ── ZeroClaw + Buzz (Rust) ───────────────────────────────────────
if (-not $SkipRust) {
  Write-Step "3/4 ZeroClaw + Buzz (cargo — can take a long time)"
  if (-not (Have "cargo")) {
    Write-Warning "Rust/cargo not found. Install from https://rustup.rs then re-run without -SkipRust."
    Write-Host "Bridge can still run in DRY_RUN against OpenAGI alone."
  } else {
    Write-Host "Building ZeroClaw release binary..."
    Push-Location $ZcPath
    cargo build --release 2>&1 | Select-Object -Last 30
    Pop-Location
    $zcBin = Join-Path $ZcPath "target\release\zeroclaw.exe"
    if (-not (Test-Path $zcBin)) {
      $zcBin = Join-Path $ZcPath "target\release\zeroclaw"
    }
    if (Test-Path $zcBin) {
      Write-Host "ZeroClaw binary: $zcBin"
    } else {
      Write-Warning "ZeroClaw build finished but binary not found — check cargo output."
    }

    Write-Host "Building Buzz CLI + buzz-acp (workspace crates)..."
    Push-Location $BuzzPath
    cargo build --release -p buzz-cli -p buzz-acp 2>&1 | Select-Object -Last 40
    Pop-Location
    Write-Host "Buzz crates build attempted (see errors above if any)."
  }
} else {
  Write-Host "Skipping Rust builds (-SkipRust)"
}

# ── Bridge (Python) ──────────────────────────────────────────────
if (-not $SkipBridge) {
  Write-Step "4/4 Bridge (Python)"
  if (-not (Have "python")) {
    throw "Python not found. Install Python 3.10+."
  }
  Push-Location (Join-Path $Root "bridge")
  python -m pip install -r requirements.txt
  python -m pytest tests -q --tb=line
  Pop-Location
} else {
  Write-Host "Skipping bridge (-SkipBridge)"
}

# ── env ──────────────────────────────────────────────────────────
$envExample = Join-Path $Root ".env.example"
$envFile = Join-Path $Root ".env"
if (-not (Test-Path $envFile) -and (Test-Path $envExample)) {
  Copy-Item $envExample $envFile
  Write-Host "Created .env from .env.example — edit secrets before live Buzz posts."
}

# PATH helper file for this session / start script
$bins = @()
$zcRelease = Join-Path $ZcPath "target\release"
$buzzRelease = Join-Path $BuzzPath "target\release"
if (Test-Path $zcRelease) { $bins += $zcRelease }
if (Test-Path $buzzRelease) { $bins += $buzzRelease }
$pathFile = Join-Path $Root "deps\path.ps1"
@"
# Generated by install.ps1 — dot-source before start
`$env:PATH = @('$($bins -join "';")') + `$env:PATH -join ';'
`$env:BUZZ_PATH = '$BuzzPath'
`$env:ZEROCLAW_PATH = '$ZcPath'
`$env:OPENAGI_PATH = '$OaPath'
`$env:OPENAGI_URL = if (`$env:OPENAGI_URL) { `$env:OPENAGI_URL } else { 'http://127.0.0.1:43210' }
`$env:ZEROCLAW_ACP_CMD = if (`$env:ZEROCLAW_ACP_CMD) { `$env:ZEROCLAW_ACP_CMD } else { 'zeroclaw acp' }
"@ | Set-Content -Encoding utf8 $pathFile

Write-Step "Install complete"
Write-Host @"

deps/
  buzz/       $BuzzPath
  zeroclaw/   $ZcPath
  openAGI/    $OaPath
bridge/       Python glue (tested)

Next (one command):
  .\scripts\start.ps1

Or dry-run bridge only:
  `$env:DRY_RUN=1; .\scripts\start.ps1 -BridgeOnly

See docs/RUN.md and docs/INTEGRATION_STATUS.md
"@
